---

- hosts: all
  vars: { nodejs_version: "node_5.x" }
  tasks:
    - apt: update_cache=yes

    # Install Node
    - apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present
    - apt_repository: repo="deb https://deb.nodesource.com/{{ nodejs_version }} {{ ansible_distribution_release }} main" update_cache=yes state=present
    - apt: name=nodejs install_recommends=no state=present

    # Install package.json
    - npm: path=/vagrant global=no state=present
      become: no
