---

- hosts: all
  tasks:
    - apt: name=apt-transport-https state=present update_cache=yes

    # Install Node
    - apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    - apt_repository: repo="deb https://deb.nodesource.com/node_10.x {{ ansible_distribution_release }} main"
    - apt: name=nodejs install_recommends=no state=present

    # Install package.json
    - npm: path=/vagrant global=no state=present
      become: no
